msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-08-13 12:20+0000\n"
"Last-Translator: \n"
"Language-Team: Romanian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100>0 && n%100<20)) ? 1 : 2);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: ro\n"
"X-Crowdin-File-ID: 670\n"
"Language: ro_RO\n"

#: redbot/cogs/audio/core/events/dpy.py:34
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:70
msgid "No DJ role found. Disabling DJ mode."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:80
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:86
msgid "Unable To Parse Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:96
#: redbot/cogs/audio/core/events/dpy.py:104
msgid "Invalid Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:97
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:114
msgid "Invalid Environment"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:115
msgid "Connection to Lavalink has been lost."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:123
msgid "No Player Available"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:124
msgid "The bot is not connected to a voice channel."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:132
#: redbot/cogs/audio/core/events/lavalink.py:83
msgid "Unable to Get Track"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:133
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:74
msgid "Couldn't get a valid track."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:84
msgid "I'm unable get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:106
msgid "Auto Play started."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:121
msgid "Now Playing"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:123
msgid "Track length: {length} | Requested by: {user}"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:144
msgid "Queue ended."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:186
msgid "Multiple Errors Detected"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:187
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:201
msgid "Track Stuck"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:202
msgid "Playback of the song has stopped due to an unexcepted error.\\n{error}"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:208
msgid "Track Error"
msgstr ""

